---
title: "MHIvsCrimes"
author: "Aileen Li"
date: "2023-03-08"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## R Markdown

```{r lib}
library(tidyverse)
```

## Tidying
```{r tidy}
# find standard error columns and delete them
med_income_base = h08_1_
colnames(med_income_base) = paste(seq_along(med_income_base))
del_col = list()

for (col in 1:ncol(h08_1_)) {
  if (col!=1 & (col-1)%%2==0) {
    del_col= append(del_col, as.character(col))
  }
}

med_income_base = med_income_base[,!names(med_income_base) %in% del_col]

# rename columns
colnames(med_income_base) = med_income_base[4,]

# remove undesired data
med_income_base = med_income_base[-(1:6),]

i = min(which(med_income_base$State=='Wyoming'))
med_income_untidy = med_income_base[1:i,] |> filter(State!="D.C.")

# make desired data tidy
med_income_tidy = med_income_untidy |> 
  pivot_longer(!State, names_to="Year", values_to="Median_Income") |> 
  filter(substr(Year, 1, 4) %in% (1992:2016))
med_income_tidy$State = toupper(med_income_tidy$State)

nrow(med_income_tidy)
```

There are 1,300 observations of the 50 states from the year 1992 to 2016. We noticed that there are years with numbers in parentheses, an indication of some kind, but we were unable to determine what these values meant because of the lack of documentation for this dataset.


